name: Terraform Unit Tests
description: Runs Terraform Unit Tests Via TerraTest
inputs:
  GITHUB_TOKEN:
    description: Workflow GitHub Token (limited permissions)
    required: true

runs:
  using: "composite"
  steps:

    - name: Setup Go
      uses: actions/setup-go@v3
      with:
        cache: true
        cache-dependency-path: test/go.sum

    - name: Unit Tests Log
      shell: bash
      if: success() || failure()
      working-directory: test
      run: |
        go test -timeout 30m 2>&1 | tee testLog.text
        result_code=${PIPESTATUS[0]}
        cat testLog.text
        exit $result_code

    - name: Unit Tests Summary
      shell: bash
      if: success() || failure()
      working-directory: test
      run: |
        cat testLog.text | grep -A 3000 'FAIL\|PASS' > testSummary.text

    - name: Report Unit Test Summary
      if: success() || failure()
      uses: actions/github-script@v6
      with:
        github-token: ${{ inputs.GITHUB_TOKEN }}
        script: |
          let stdout = '';
          let stderr = '';

          const options = {};
          options.listeners = {
            stdout: (data) => {
              stdout += data.toString();
            },
            stderr: (data) => {
              stderr += data.toString();
            }
          };
          await exec.exec('cat', ['test/testSummary.text'], options);

          const output = `### Unit Tests Results
          <details><summary>Show Results</summary>

          \`\`\`\n
          ${stdout}
          \`\`\`

          </details>`;
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: output
          })
